version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    environment:
      CI: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy-auto:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "auto-introspection-app"
    steps:
      - checkout
      - run:
          name: Deploy auto environment to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  smoke-test-auto:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "auto-introspection-app"
    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com

  deploy-test:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "test-introspection-app"
    steps:
      - checkout
      - run:
          name: Deploy test environment to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  smoke-test-test:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "test-introspection-app"
    steps:
      - run:
          name: Smoke test for test environment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com

  deploy-staging:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "staging-introspection-app"
    steps:
      - checkout
      - run:
          name: Deploy test environment to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  smoke-test-staging:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "staging-introspection-app"
    steps:
      - run:
          name: Smoke test for staging environment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test-auto:
          requires:
            - deploy-auto
      - hold:
          type: approval
          requires:
            - deploy-auto
      - deploy-test:
          requires:
            - hold
      - smoke-test-test:
          requires:
            - deploy-test
      - hold-staging:
          type: approval
          requires:
            - deploy-test
      - deploy-staging:
          requires:
            - hold-staging
      - smoke-test-staging:
          requires:
            - deploy-staging
