version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm run build

      - run: mkdir -p /tmp/build

      - run: cp -r build /tmp

      - persist_to_workspace:
          root: /tmp
          paths:
            - build/*

  deploy-auto:
    docker:
      - image: circleci/node:10.15.3

    environment:
      NETLIFY_SITE_ID: '6a31461c-b55e-4aed-9477-4e34df87bdae'

    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Deploy auto environment to Netlify
          command: npx netlify-cli deploy --prod --dir=/tmp/build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-auto:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'auto-introspection-app'

    steps:
      - run:
          name: Smoke test for auto environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

  deploy-qa:
    docker:
      - image: circleci/node:10.15.3

    environment:
      NETLIFY_SITE_ID: '9d76611c-3f91-42e4-bcf5-290c6e8de93e'

    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Deploy qa environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-qa:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'qa-introspection-app'

    steps:
      - run:
          name: Smoke test for qa environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

  deploy-staging:
    docker:
      - image: circleci/node:10.15.3

    environment:
      NETLIFY_SITE_ID: '67d966d5-32bd-49b5-907c-b127e81ffa78'

    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Deploy staging environment to Netlify
          command: npx netlify-cli deploy -p --dir=/tmp/build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

  smoke-test-staging:
    docker:
      - image: buildpack-deps:trusty

    environment:
      NETLIFY_APP_NAME: 'staging-introspection-app'

    steps:
      - run:
          name: Smoke test for staging environment
          command: curl --fail https://$NETLIFY_APP_NAME.netlify.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test-auto:
          requires:
            - deploy-auto
      - hold:
          type: approval
          requires:
            - deploy-auto
      - deploy-qa:
          requires:
            - hold
      - smoke-test-qa:
          requires:
            - deploy-qa
      - hold-staging:
          type: approval
          requires:
            - deploy-qa
      - deploy-staging:
          requires:
            - hold-staging
      - smoke-test-staging:
          requires:
            - deploy-staging
